---
- name: install pbench-agent
  hosts: pbench_vms
  remote_user: cloud-user
  become: yes
  # The default value ('production') can be overriddent by cenv, a host-specific
  # inventory variable.
  vars:
    pbench_configuration_environment: "{{ cenv | default('production') }}"
  roles:
    - pbench_repo_install
    - pbench_agent_install
    - pbench_agent_config
